// Generated by scripts/generate-deployments.ts — do not edit by hand.
// Regenerate with `pnpm deployments` after redeploying.

import type {Deployment} from './chains';

/** Addresses that actually landed on chain, read from Foundry's broadcast receipt. */
export const GENERATED_DEPLOYMENTS: Record<number, Deployment> = {
  31337: {
    attributionRegistry: "0x7a2088a1bFc9d81c55368AE168C2C02570cB814F",
    attestationVerifier: "0x09635F643e140090A9A8Dcd712eD6285858ceBef",
    reputationRegistry: "0xc5a5C42992dECbae36851359345FE25997F5C42d",
    oracleCoordinator: "0x67d269191c92Caf3cD7723F116c85e6E9bf55933",
    escrowVault: "0xE6E340D132b5f46d1e472DebcD681B2aBc16e57E",
    campaignRegistry: "0xc3e53F4d16Ae77Db1c982e75a937B9f60FE63690",
    boney: "0xa82fF9aFd8f496c3d6ac40E2a0F282E47488CFc9",
    startBlock: 44n,
  },
  84532: {
    attributionRegistry: "0x2aa5bbFC8dfa135e658d2F77e5bC9E2413412FfB",
    attestationVerifier: "0xeDB447b04E67aFc825Cd83b5c9d20755a0e6DBd0",
    reputationRegistry: "0x6F3089a5Ce3a92d7653ACeF4529A8A20436f44D5",
    oracleCoordinator: "0xcCA28482CcbAb684633D0D562Ce348bbdcE7C95c",
    escrowVault: "0xA097769736Dd9494CdDa37673B05E0c929A7A49A",
    campaignRegistry: "0x1aa651F1941EfCaAD8156bdB267B18ADdEb0b5aD",
    boney: "0x7B27402D3F2170f4CFc521c6De992a908BBe92e1",
    startBlock: 45477925n,
  },
};
