// Generated by scripts/generate-deployments.ts — do not edit by hand.
// Regenerate with `pnpm deployments` after redeploying.

import type {Deployment} from './chains';

/** Addresses that actually landed on chain, read from Foundry's broadcast receipt. */
export const GENERATED_DEPLOYMENTS: Record<number, Deployment> = {
  31337: {
    attributionRegistry: "0x7a2088a1bFc9d81c55368AE168C2C02570cB814F",
    attestationVerifier: "0x09635F643e140090A9A8Dcd712eD6285858ceBef",
    reputationRegistry: "0xc5a5C42992dECbae36851359345FE25997F5C42d",
    oracleCoordinator: "0x67d269191c92Caf3cD7723F116c85e6E9bf55933",
    escrowVault: "0xE6E340D132b5f46d1e472DebcD681B2aBc16e57E",
    campaignRegistry: "0xc3e53F4d16Ae77Db1c982e75a937B9f60FE63690",
    boney: "0xa82fF9aFd8f496c3d6ac40E2a0F282E47488CFc9",
    startBlock: 44n,
  },
  84532: {
    attributionRegistry: "0x1E5d273B2CBdF55a07888518A479B5E00C7323c8",
    attestationVerifier: "0x2867dF1C79923BAF5815a23Aec94492B3140971D",
    reputationRegistry: "0x093F2536fC8a655d206c243fC76FDe4D678C5335",
    oracleCoordinator: "0x8C0434a043b52cd750b8659261D745F7C36b42a0",
    escrowVault: "0xcaD74fF59A30D1c4d3433A32D2d1fca773a0DbFf",
    campaignRegistry: "0x0FF749bB1566A2C4b74DdC03Ac0F516DEe8e1C1A",
    boney: "0x1B6E0718755AeC3029583b85D05692Dd69419707",
    startBlock: 45510196n,
  },
};
