// Generated by scripts/generate-deployments.ts — do not edit by hand.
// Regenerate with `pnpm deployments` after redeploying.

import type {Deployment} from './chains';

/** Addresses that actually landed on chain, read from Foundry's broadcast receipt. */
export const GENERATED_DEPLOYMENTS: Record<number, Deployment> = {
  31337: {
    attributionRegistry: "0x6f55FcDA50EF80892fD99636B8b4f1086d584BAa",
    attestationVerifier: "0x6c81021e53e1f9C07a20C6BE7e77Fdd964CB73a2",
    reputationRegistry: "0xeF5D0fB1f56FFec24dd3A376fb54B22355126a4A",
    oracleCoordinator: "0xc12e7202F628c0cc488554dcFC8C2F2ce3323e4C",
    escrowVault: "0x65F79Abb40Aa89CD2e7EFD15dAda200b4d50bF1B",
    campaignRegistry: "0x424b10cB08C640A96a789e6ef6e06f99264ec8eC",
    boney: "0x259197Ae7FdC1937f724667d094cd492bcD2fFBa",
    eventMetricKpiVerifier: "0x07836767a4c7e9569b0a0275f430DD011F50D0Be",
    guardedKpiVerifier: "0x87C235bbc36462c5836371a4016ed61EA4c87db7",
    touchWindowVerifier: "0xeb7F8C4D8Fa6740349AaF7A7Cc64F12954c91A34",
    startBlock: 45710232n,
  },
  84532: {
    attributionRegistry: "0x83e507246C584471A5645aed1Ab086B174ec5a29",
    attestationVerifier: "0xb4797645D1C323bF471C87830A391ED984647DCc",
    reputationRegistry: "0x87bc44ec1f80CA8d9520D038cd10E7Ccf73F087c",
    oracleCoordinator: "0xC6e692D1e0954Af5AD5818A07dB7C657c6Fcc9B8",
    escrowVault: "0x6ae4fe63517e5BB7CA1bB9385997f9545A586312",
    campaignRegistry: "0x6427217ea49EddeB51471005830962a6f0Df8e24",
    boney: "0xe10EF18B70C536Fc0bCadADe70c6f7bfE6b262D0",
    eventMetricKpiVerifier: "0xa0eee1757a1a01d987B0c638c6703e0BA83bAa69",
    guardedKpiVerifier: "0x4f9F7bF5B80E546796C7D292c956DF525fCe7eb4",
    touchWindowVerifier: "0xE5f48afC387FE8DE1644a62e6482F8301C6DfE47",
    startBlock: 45856660n,
  },
};
