/**
 * Extracts contract ABIs from Foundry build artifacts into `src/lib/abis/`.
 *
 * Hand-copied ABIs drift silently: a contract changes, the frontend keeps the stale shape, and
 * the mismatch only surfaces as a decode error at runtime. Generating them from `out/` means the
 * frontend cannot disagree with the compiled contracts.
 *
 * Usage: pnpm abis
 */
import {readFileSync, writeFileSync, mkdirSync, existsSync} from "node:fs";
import {resolve, dirname} from "node:path";
import {fileURLToPath} from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const FOUNDRY_OUT = resolve(here, "../../out");
const ABI_DIR = resolve(here, "../src/lib/abis");

/** Contracts the frontend talks to, and the artifact each one lives in. */
export const CONTRACTS = [
  {name: "Boney", artifact: "Boney.sol/Boney.json"},
  {name: "Campaign", artifact: "Campaign.sol/Campaign.json"},
  {name: "CampaignRegistry", artifact: "CampaignRegistry.sol/CampaignRegistry.json"},
  {name: "EscrowVault", artifact: "EscrowVault.sol/EscrowVault.json"},
  {name: "AttributionRegistry", artifact: "AttributionRegistry.sol/AttributionRegistry.json"},
  {name: "ReputationRegistry", artifact: "ReputationRegistry.sol/ReputationRegistry.json"},
  {name: "AttestationVerifier", artifact: "AttestationVerifier.sol/AttestationVerifier.json"},
  {name: "OracleCoordinator", artifact: "OracleCoordinator.sol/OracleCoordinator.json"},
  {
    name: "EventMetricKpiVerifier",
    artifact: "EventMetricKpiVerifier.sol/EventMetricKpiVerifier.json",
  },
  {name: "GuardedKpiVerifier", artifact: "GuardedKpiVerifier.sol/GuardedKpiVerifier.json"},
  {name: "TouchWindowVerifier", artifact: "TouchWindowVerifier.sol/TouchWindowVerifier.json"},
  {name: "IERC20", artifact: "IERC20.sol/IERC20.json"},
  {name: "IERC20Metadata", artifact: "IERC20Metadata.sol/IERC20Metadata.json"},
] as const;

export type AbiEntry = {
  type: string;
  name?: string;
  inputs?: unknown[];
  outputs?: unknown[];
  stateMutability?: string;
};

export function readAbi(artifactPath: string): AbiEntry[] {
  const full = resolve(FOUNDRY_OUT, artifactPath);
  if (!existsSync(full)) {
    throw new Error(`Artifact not found: ${full}\nRun \`forge build\` in the repo root first.`);
  }
  const parsed = JSON.parse(readFileSync(full, "utf8")) as {abi?: AbiEntry[]};
  if (!parsed.abi) throw new Error(`No \`abi\` key in ${artifactPath}`);
  return parsed.abi;
}

function emit(name: string, abi: AbiEntry[]): string {
  return [
    "// Generated by scripts/extract-abis.ts — do not edit by hand.",
    "// Regenerate with `pnpm abis` after changing the contracts.",
    "",
    `export const ${name}Abi = ${JSON.stringify(abi, null, 2)} as const;`,
    "",
  ].join("\n");
}

export function main(): void {
  mkdirSync(ABI_DIR, {recursive: true});

  const index: string[] = [
    "// Generated by scripts/extract-abis.ts — do not edit by hand.",
    "",
  ];

  for (const {name, artifact} of CONTRACTS) {
    const abi = readAbi(artifact);
    writeFileSync(resolve(ABI_DIR, `${name}.ts`), emit(name, abi));
    index.push(`export {${name}Abi} from "./${name}";`);
    console.log(`  ${name.padEnd(22)} ${abi.length} entries`);
  }

  writeFileSync(resolve(ABI_DIR, "index.ts"), index.join("\n") + "\n");
  console.log(`\nWrote ${CONTRACTS.length} ABIs to src/lib/abis/`);
}

// Only run when invoked directly, so tests can import the helpers.
if (process.argv[1] && process.argv[1].endsWith("extract-abis.ts")) {
  main();
}
