/**
 * Generates `src/lib/deployments.ts` from Foundry's broadcast receipt.
 *
 * Hand-transcribing addresses is exactly the class of error that shipped a bricked vault in the
 * contract phase — one wrong character is silent until a call reverts. The broadcast receipt is
 * the source of truth for what actually landed on chain.
 *
 * Usage: pnpm deployments [chainId]   (default 31337)
 */
import {readFileSync, writeFileSync, mkdirSync, existsSync} from "node:fs";
import {resolve, dirname} from "node:path";
import {fileURLToPath} from "node:url";
import {getAddress} from "viem";

const here = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(here, "../..");

type BroadcastTx = {
  transactionType?: string;
  contractName?: string | null;
  contractAddress?: string | null;
};

/** Maps Solidity contract names to the keys the app's `Deployment` type uses. */
const KEY_BY_CONTRACT: Record<string, string> = {
  Boney: "boney",
  CampaignRegistry: "campaignRegistry",
  EscrowVault: "escrowVault",
  AttributionRegistry: "attributionRegistry",
  ReputationRegistry: "reputationRegistry",
  AttestationVerifier: "attestationVerifier",
  OracleCoordinator: "oracleCoordinator",
};

export function readBroadcast(chainId: number): Record<string, string> {
  const path = resolve(
    REPO_ROOT,
    `broadcast/DeployBoney.s.sol/${chainId}/run-latest.json`,
  );
  if (!existsSync(path)) {
    throw new Error(
      `No broadcast receipt at ${path}\n` +
        `Deploy first:\n` +
        `  PRIVATE_KEY=0x… BONEY_INITIAL_ATTESTOR=0x… forge script ` +
        `script/DeployBoney.s.sol:DeployBoney --rpc-url http://127.0.0.1:8545 --broadcast`,
    );
  }

  const parsed = JSON.parse(readFileSync(path, "utf8")) as {transactions?: BroadcastTx[]};
  const out: Record<string, string> = {};

  for (const tx of parsed.transactions ?? []) {
    if (tx.transactionType !== "CREATE") continue;
    const name = tx.contractName;
    if (!name || !tx.contractAddress) continue;
    const key = KEY_BY_CONTRACT[name];
    if (!key) continue;
    // Checksum the address: viem rejects malformed ones, so a typo cannot survive this step.
    out[key] = getAddress(tx.contractAddress);
  }

  const missing = Object.values(KEY_BY_CONTRACT).filter((k) => !(k in out));
  if (missing.length > 0) {
    throw new Error(`Broadcast receipt is missing: ${missing.join(", ")}`);
  }

  return out;
}

function emit(chainId: number, addresses: Record<string, string>): string {
  const entries = Object.entries(addresses)
    .map(([k, v]) => `    ${k}: "${v}",`)
    .join("\n");

  return [
    "// Generated by scripts/generate-deployments.ts — do not edit by hand.",
    "// Regenerate with `pnpm deployments` after redeploying.",
    "",
    "import type {Deployment} from './chains';",
    "",
    "/** Addresses that actually landed on chain, read from Foundry's broadcast receipt. */",
    "export const GENERATED_DEPLOYMENTS: Record<number, Deployment> = {",
    `  ${chainId}: {`,
    entries,
    "  },",
    "};",
    "",
  ].join("\n");
}

function main(): void {
  const chainId = Number(process.argv[2] ?? 31337);
  const addresses = readBroadcast(chainId);

  const outDir = resolve(here, "../src/lib");
  mkdirSync(outDir, {recursive: true});
  writeFileSync(resolve(outDir, "deployments.ts"), emit(chainId, addresses));

  console.log(`Chain ${chainId}:`);
  for (const [k, v] of Object.entries(addresses)) {
    console.log(`  ${k.padEnd(20)} ${v}`);
  }
  console.log(`\nWrote src/lib/deployments.ts`);
}

if (process.argv[1]?.endsWith("generate-deployments.ts")) {
  main();
}
