// Generated by scripts/extract-abis.ts — do not edit by hand.
// Regenerate with `pnpm abis` after changing the contracts.

export const EventMetricKpiVerifierAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "owner_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "reporter_",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "advanceCheckpoint",
    "inputs": [
      {
        "name": "campaign",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "kpiIndex",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "scannedUpToBlock",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "checkpointOf",
    "inputs": [
      {
        "name": "campaign",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "kpiIndex",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "configOf",
    "inputs": [
      {
        "name": "campaign",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "kpiIndex",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct EventMetricKpiVerifier.KpiConfig",
        "components": [
          {
            "name": "targetContract",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "eventSignature",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "userParamIndex",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "valueParamIndex",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "aggregation",
            "type": "uint8",
            "internalType": "enum IEventMetricKpiVerifier.Aggregation"
          },
          {
            "name": "scale",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "windowStartBlock",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "windowEndBlock",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "configured",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "epoch",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "kpiConfigs",
    "inputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "targetContract",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "eventSignature",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "userParamIndex",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "valueParamIndex",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "aggregation",
        "type": "uint8",
        "internalType": "enum IEventMetricKpiVerifier.Aggregation"
      },
      {
        "name": "scale",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "windowStartBlock",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "windowEndBlock",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "configured",
        "type": "bool",
        "internalType": "bool"
      },
      {
        "name": "epoch",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "lastReportedAt",
    "inputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "lastScannedBlock",
    "inputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "observedProgressOf",
    "inputs": [
      {
        "name": "campaign",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "kpiIndex",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "user",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "owner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "renounceOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "reportBatch",
    "inputs": [
      {
        "name": "campaign",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "kpiIndex",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "users",
        "type": "address[]",
        "internalType": "address[]"
      },
      {
        "name": "totals",
        "type": "uint256[]",
        "internalType": "uint256[]"
      },
      {
        "name": "scannedUpToBlock",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "reportVerifiedTotal",
    "inputs": [
      {
        "name": "campaign",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "kpiIndex",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "user",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "verifiedTotal",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "reporter",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "setKpiConfig",
    "inputs": [
      {
        "name": "campaign",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "kpiIndex",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "targetContract",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "eventSignature",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "userParamIndex",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "aggregation",
        "type": "uint8",
        "internalType": "enum IEventMetricKpiVerifier.Aggregation"
      },
      {
        "name": "valueParamIndex",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "scale",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "windowStartBlock",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "windowEndBlock",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setReporter",
    "inputs": [
      {
        "name": "newReporter",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "transferOwnership",
    "inputs": [
      {
        "name": "newOwner",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "verifiedTotalOf",
    "inputs": [
      {
        "name": "campaign",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "kpiIndex",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "user",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "verifiedTotals",
    "inputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "verify",
    "inputs": [
      {
        "name": "campaign",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "kpiIndex",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "user",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "credited",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "CheckpointAdvanced",
    "inputs": [
      {
        "name": "campaign",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "kpiIndex",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "scannedUpToBlock",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "KpiConfigured",
    "inputs": [
      {
        "name": "campaign",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "kpiIndex",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "targetContract",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "eventSignature",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      },
      {
        "name": "userParamIndex",
        "type": "uint8",
        "indexed": false,
        "internalType": "uint8"
      },
      {
        "name": "aggregation",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum IEventMetricKpiVerifier.Aggregation"
      },
      {
        "name": "valueParamIndex",
        "type": "uint8",
        "indexed": false,
        "internalType": "uint8"
      },
      {
        "name": "scale",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "windowStartBlock",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "windowEndBlock",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "KpiTotalsInvalidated",
    "inputs": [
      {
        "name": "campaign",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "kpiIndex",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "epoch",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferred",
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ReporterUpdated",
    "inputs": [
      {
        "name": "oldReporter",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newReporter",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "VerifiedTotalReported",
    "inputs": [
      {
        "name": "campaign",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "kpiIndex",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "user",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "verifiedTotal",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "BadWindow",
    "inputs": [
      {
        "name": "windowStartBlock",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "windowEndBlock",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "CheckpointRegression",
    "inputs": [
      {
        "name": "current",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "provided",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "EmptyEventSignature",
    "inputs": []
  },
  {
    "type": "error",
    "name": "KpiNotConfigured",
    "inputs": [
      {
        "name": "campaign",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "kpiIndex",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "LengthMismatch",
    "inputs": [
      {
        "name": "users",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "totals",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotReporter",
    "inputs": [
      {
        "name": "caller",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "OwnableInvalidOwner",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "OwnableUnauthorizedAccount",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "PastReportWindow",
    "inputs": [
      {
        "name": "windowEndBlock",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "provided",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  }
] as const;
