// Generated by scripts/extract-abis.ts — do not edit by hand.
// Regenerate with `pnpm abis` after changing the contracts.

export const TransferVerifierAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "oracle_",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "TRANSFER_SIGNATURE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "oracle",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IEventOracle"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "verify",
    "inputs": [
      {
        "name": "campaign",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "kpiIndex",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "user",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "newTotal",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "evidence",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "params",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "credited",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "error",
    "name": "InvalidTransferDirection",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MissingOracle",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TransferAmountExceeded",
    "inputs": [
      {
        "name": "verifiedAmount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "reportedAmount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  }
] as const;
